### ISSUE TITLE
Problem with UNO

### ISSUE THREAD

**Issue by suvodip1212** [OpenBCI/OpenBCI-V2hardware-DEPRECATED#28]
I am having problems with interfacing my ads1299FE with arduino UNO. I was trying to stream data as txt using the ADSMangager but it seems i am getting some gibberish values also the registers seem to be not read properly. Could any one suggest a suitable circuit diagram for UNO and ads1299 daughter board?

**Comment by biomurph** [comment]
Hi suvodip1212
What 'daughter board' are you using?

We interfaced the ADS1299 to the UNO via the SPI bus (pins 13,12,11) and you also need pins to connect the Chip Select, DRDY, and RESET pins of the ADS. Those are listed in the ADS1299Manager.h file.

What sort of gibberish are you getting?

**Comment by suvodip1212** [comment]
The daughter board:http://www.ti.com/tool/ads1299eegfe-pdk 
All the registers read are zeroes. Even with test signals i tested the board with TI software it seems to be working fine.

**Comment by biomurph** [comment]
I have one of those boards and have not used it in years. The UNO runs at 5V, and the digital part of the ADS runs at 3.3V. Are you using a level shifter?

**Comment by suvodip1212** [comment]
I was. but i guess due to some issue it got damaged. let me replace it and get back to you. I hope clksel, START pins require no input.

**Comment by joelSensor** [comment]
You can't let the clksel pin or the start pin float. There is power and ground on the ads module. Use those to set your pins. Don't let any of those control pins float

**Comment by suvodip1212** [comment]
Is there a schematic for these pins or i use CLKSEL, RESET, and PWDN pins to the 3.3V. And I am connecting pins 4, 10, and 18 of J3 to ground.

**Comment by joelSensor** [comment]
I don't have the docs in front of me, but you have to look at the schematic of the Deb module and the ads datasheet to confirm where the pins are broken out and how to assert them

**Comment by suvodip1212** [comment]
ok i will check out the dev board and identify the changes.

**Comment by suvodip1212** [comment]
![obci_v3_8bit-schematic](https://cloud.githubusercontent.com/assets/27431612/25053131/0879ea02-2173-11e7-91e9-56e9eedb0f12.jpg) in this schema the control pins are floating if you can suggest changes. any help is appreciated.

**Comment by sL0v3r** [comment]
i have similar problem, but i read only 1

I use arduino Uno and level shifter,bidirectional bus, 5V->3,3V. All these pin are with 3.3V
13 - SCLK*
12- MISO*
11-MOSI*
10- CS*
9-RESET*
8 -DRDY*
7-START/CS*
Power Source are provided from MMB0 of the TI Kit.
I run example1, but all register are set to 1 (i add to ads.inizialize funciont the "false" argument for daisychain). Library used ADS1299.h
Why i cannot read correctly the register value???

**Comment by suvodip1212** [comment]
ADS.initialize(8,9,10,4,true); // (DRDY pin, RST pin, CS pin, SCK frequency in MHz);
  pinMode(6,INPUT);  digitalWrite(6,HIGH); //activate pullup...for detecting which version of OpenBCI PCB
  pinMode(7,OUTPUT); digitalWrite(7,LOW);  //act as a ground pin...for detecting which version of OpenBCI 
which pin to connect in 6 and 7??

**Comment by biomurph** [comment]
pins 6 and 7 were specific to our early hardware designs. They don't need to be connected to the TI dev board.

**Comment by suvodip1212** [comment]
![image](https://cloud.githubusercontent.com/assets/27431612/25606030/b7387cea-2f2c-11e7-87f2-cc66cc22a211.png)
 I am able to read this finally. I still need to figure out the connections properly.

**Comment by sL0v3r** [comment]
Great suvodip1212!!! what was the problem?

**Comment by suvodip1212** [comment]
I will share the diagram tomorrow as i left the lab today but, i am still
unable to read the data on some instances.

**Comment by biomurph** [comment]
Hey suvodip1212! That's great!
Please do share the lashup

**Comment by suvodip1212** [comment]
![p_20170505_172009](https://cloud.githubusercontent.com/assets/27431612/25855840/ed62c92c-34f1-11e7-94ff-34bcb8483750.jpg) here is the schema i used . still buggy eventhough.
Sorry for the delay. if  anyone makes modification please let me know.

**Comment by srihasreb** [comment]
when i am powering up my ads1299 boards the IC's are heating like anything  ,can anyone please drop the solution here

**Comment by srihasreb** [comment]
i am unable to read the data in the registers of ads1299 , it is always showing the results as all zeros or all ones, can any one plzz help

**Comment by rastamoeinzadeh** [comment]
Hi, would you please say how did that?
I still get 0x00 or 0xFF. I don't know it's because of code or my connections. Did you change anything in the code?

**Comment by biomurph** [comment]
We are not supporting this hardware or firmware any more. I'm sorry, but we just don't have the bandwidth and the last time I looked at it was years ago.
